### PR TITLE
Correct apparent typo in Awk.java

### PR DESCRIPTION
**Pull request by paulkrause88**
The comment indicates this branch should be taken when the compile flag is set, so this is probably what the author intended.

### CODE REVIEW

**Comment by hoijui** [comment]
thanks! :-)
and sorry for the long delay.

i did not know anybody is using it... do you mind telling me what you do with it? :-)

**Comment by hoijui** [comment]
thanks! :-)
and sorry for the long delay.

i did not know anybody is using it... do you mind telling me what you do with it? :-)

**Comment by paulkrause88** [comment]
Not a problem.  I'm not actually using it at the moment.  My original use case was upgrading some config files in a cross-platform way, but it looks like it will be easier to build that functionality into the app than to use an awk script.  Jawk is interesting to play with, though.  I wish the original version history was still available.

**Comment by hoijui** [comment]
ahh i see...
yeah... i also think that is a pitty.
i also just took over because.. i wanted to use awk scripts to generate sources in a maven based project. i also started a maven plugin for that, but then stopped mid-way (whitle testing the alpha).

**Pull request merged**
